### ISSUE TITLE
Aborted (core dumped) on Arch linux

### ISSUE THREAD

**Issue by superbonaci** [srtlg/lfhex#1]
Installed `lfhex` from AUR (https://aur.archlinux.org/packages/lfhex), this is the error:
````
$ lfhex
/usr/include/c++/12.1.1/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = QRect; _Alloc = std::allocator<QRect>; reference = QRect&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
````

The version is as follows:
````
$ pacman -Q lfhex
lfhex 0.42-2
````

**Comment by srtlg** [comment]
this is a weird error as it doesn't appear when compiled as debug

**Comment by srtlg** [comment]
```gdb lfhex

(gdb) run
/usr/include/c++/12.1.1/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = QRect; _Alloc = std::allocator<QRect>; reference = QRect&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6cbd4dc in ?? () from /usr/lib/libc.so.6
(gdb) btg
Undefined command: "btg".  Try "help".
(gdb) bt
#0  0x00007ffff6cbd4dc in  () at /usr/lib/libc.so.6
#1  0x00007ffff6c6d998 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff6c5753d in abort () at /usr/lib/libc.so.6
#3  0x00007ffff6ff6112 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) (file=<optimized out>, line=<optimized out>, function=<optimized out>, condition=<optimized out>) at /usr/src/debug/gcc/libstdc++-v3/src/c++11/debug.cc:60
#4  0x000055555556b115 in  ()
#5  0x0000555555568578 in  ()
#6  0x000055555556b3e0 in  ()
#7  0x000055555556d3e8 in  ()
#8  0x000055555556466a in  ()
#9  0x00007ffff6c582d0 in  () at /usr/lib/libc.so.6
#10 0x00007ffff6c5838a in __libc_start_main () at /usr/lib/libc.so.6
#11 0x0000555555564845 in  ()
(gdb) info proc mapping
          Start Addr           End Addr       Size     Offset  Perms  objfile
      0x555555554000     0x555555563000     0xf000        0x0  r--p   /usr/bin/lfhex
      0x555555563000     0x555555578000    0x15000     0xf000  r-xp   /usr/bin/lfhex
      0x555555578000     0x555555582000     0xa000    0x24000  r--p   /usr/bin/lfhex
      0x555555582000     0x555555584000     0x2000    0x2e000  r--p   /usr/bin/lfhex
      0x555555584000     0x555555586000     0x2000    0x30000  rw-p   /usr/bin/lfhex
```

**Comment by srtlg** [comment]
```
gdb) bt
#0  0x00007ffff6cbd4dc in  () at /usr/lib/libc.so.6
#1  0x00007ffff6c6d998 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff6c5753d in abort () at /usr/lib/libc.so.6
#3  0x00007ffff6ff6112 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*)
    (file=file@entry=0x5555555781c0 "/usr/include/c++/12.1.1/bits/stl_vector.h", line=line@entry=1123, function=function@entry=0x5555555796c8 "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = QRect; _Alloc = std::allocator<QRect>; reference = QRect&; size_type = long unsigned int]", condition=condition@entry=0x55555557801c "__n < this->size()") at /usr/src/debug/gcc/libstdc++-v3/src/c++11/debug.cc:60
#4  0x000055555556b115 in std::vector<QRect, std::allocator<QRect> >::operator[](unsigned long) (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/12.1.1/bits/stl_vector.h:1123
#5  std::vector<QRect, std::allocator<QRect> >::operator[](unsigned long) (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/12.1.1/bits/stl_vector.h:1121
#6  HexEditor::resizeEvent(QResizeEvent*) (this=0x55555564df70, e=<optimized out>) at hexEditor.cpp:699
#7  0x0000555555568578 in HexEditor::calculateFontMetrics() (this=0x55555564df70) at hexEditor.cpp:230
#8  0x000055555556b3e0 in HexEditor::HexEditor(QWidget*) (this=this@entry=0x55555564df70, parent=parent@entry=0x55555565f3e0) at hexEditor.cpp:63
#9  0x000055555556d3e8 in HexGui::HexGui(QWidget*) (this=this@entry=0x555555675320, p=p@entry=0x0) at hexGui.cpp:43
#10 0x000055555556466a in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at driver.cpp:81
```

**Comment by superbonaci** [comment]
Thanks a lot 😊
